export const EXCHANGE_RATE_FETCH_INIT = "EXCHANGE_RATE_FETCH_INIT";
export const EXCHANGE_RATE_FETCH_SUCCESS = "EXCHANGE_RATE_FETCH_SUCCESS";
export const EXCHANGE_RATE_FETCH_ERROR = "EXCHANGE_RATE_FETCH_ERROR";

export const ACTIVE_BID_START_INIT = "ACTIVE_BID_START_INIT";
export const ACTIVE_BID_START_SUCCESS = "ACTIVE_BID_START_SUCCESS";
export const ACTIVE_BID_START_ERROR = "ACTIVE_BID_START_ERROR";

export const ACTIVE_BID_CANCEL_INIT = "ACTIVE_BID_CANCEL_INIT";
export const ACTIVE_BID_CANCEL_SUCCESS = "ACTIVE_BID_CANCEL_SUCCESS";
export const ACTIVE_BID_CANCEL_ERROR = "ACTIVE_BID_CANCEL_ERROR";

export const ACTIVE_BID_FETCH_INIT = "ACTIVE_BID_FETCH_INIT";
export const ACTIVE_BID_FETCH_SUCCESS = "ACTIVE_BID_FETCH_SUCCESS";
export const ACTIVE_BID_FETCH_ERROR = "ACTIVE_BID_FETCH_ERROR";

export const ACTIVE_BID_MATCH = "ACTIVE_BID_MATCH";

export const AUTH_PROVIDER_INIT = "AUTH_PROVIDER_INIT";
export const AUTH_PROVIDER_SUCCESS = "AUTH_PROVIDER_SUCCESS";
export const AUTH_PROVIDER_ERROR = "AUTH_PROVIDER_ERROR";

export const AUTH_CLEAN_UP = "AUTH_CLEAN_UP";

export const HISTORY_FETCH_INIT = "HISTORY_FETCH_INIT";
export const HISTORY_FETCH_SUCCESS = "HISTORY_FETCH_SUCCESS";
export const HISTORY_FETCH_ERROR = "HISTORY_FETCH_ERROR";
