export const EXCHANGE_RATE_UPDATE = "EXCHANGE_RATE_UPDATE";
export const EXCHANGE_RATE_FETCH_ERROR = "EXCHANGE_RATE_FETCH_ERROR";
export const ACTIVE_BID_SET = "ACTIVE_BID_SET";
export const ACTIVE_BID_CLEAR = "ACTIVE_BID_CLEAR";
export const ACTIVE_BID_FETCH = "ACTIVE_BID_FETCH";
export const ACTIVE_BID_FETCH_ERROR = "ACTIVE_BID_FETCH_ERROR";
