export const EXCHANGE_RATE_UPDATE = "EXCHANGE_RATE_UPDATE";
export const EXCHANGE_RATE_FETCH_ERROR = "EXCHANGE_RATE_FETCH_ERROR";

export const ACTIVE_BID_START = "ACTIVE_BID_START";
export const ACTIVE_BID_CANCEL = "ACTIVE_BID_CANCEL";
export const ACTIVE_BID_FETCH = "ACTIVE_BID_FETCH";
export const ACTIVE_BID_FETCH_ERROR = "ACTIVE_BID_FETCH_ERROR";
export const ACTIVE_BID_MATCH = "ACTIVE_BID_MATCH";
